# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
from pydantic import BaseModel


StreamStateValueT = typing.TypeVar("StreamStateValueT")


class StreamState(BaseModel, typing.Generic[StreamStateValueT]):
    value: StreamStateValueT
    state: typing_extensions.Literal["Pending", "Incomplete", "Complete"]


# #########################################################################
# Generated classes (4)
# #########################################################################


class AgentSuggestion(BaseModel):
    summary: typing.Optional[str] = None
    meal_plan: typing.List[str]
    calorie_management: typing.List[str]
    weight_management: typing.List[str]
    hydration: typing.List[str]
    lifestyle: typing.List[str]


class HealthAgentContext(BaseModel):
    metric: typing.Optional["HealthMetric"] = None
    preference: typing.Optional["HealthPreference"] = None


class HealthMetric(BaseModel):
    weight_kg: typing.Optional[float] = None
    body_fat_percent: typing.Optional[float] = None
    bmi: typing.Optional[float] = None
    muscle_percent: typing.Optional[float] = None
    water_percent: typing.Optional[float] = None
    recorded_at: typing.Optional[str] = None
    note: typing.Optional[str] = None


class HealthPreference(BaseModel):
    target_weight_kg: typing.Optional[float] = None
    calorie_budget_kcal: typing.Optional[int] = None
    dietary_preference: typing.Optional[str] = None
    activity_level: typing.Optional[str] = None
    sleep_goal_hours: typing.Optional[float] = None
    hydration_goal_liters: typing.Optional[float] = None


# #########################################################################
# Generated type aliases (0)
# #########################################################################
