# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
from baml_py import type_builder
from baml_py import baml_py

# These are exports, not used here, hence the linter is disabled
from baml_py.baml_py import FieldType, EnumValueBuilder, EnumBuilder, ClassBuilder  # noqa: F401 # pylint: disable=unused-import
from .globals import DO_NOT_USE_DIRECTLY_UNLESS_YOU_KNOW_WHAT_YOURE_DOING_RUNTIME


class TypeBuilder(type_builder.TypeBuilder):
    def __init__(self):
        super().__init__(
            classes=set(
                [
                    "AgentSuggestion",
                    "HealthAgentContext",
                    "HealthMetric",
                    "HealthPreference",
                ]
            ),
            enums=set([]),
            runtime=DO_NOT_USE_DIRECTLY_UNLESS_YOU_KNOW_WHAT_YOURE_DOING_RUNTIME,
        )

    # #########################################################################
    # Generated enums 0
    # #########################################################################

    # #########################################################################
    # Generated classes 4
    # #########################################################################

    @property
    def AgentSuggestion(self) -> "AgentSuggestionViewer":
        return AgentSuggestionViewer(self)

    @property
    def HealthAgentContext(self) -> "HealthAgentContextViewer":
        return HealthAgentContextViewer(self)

    @property
    def HealthMetric(self) -> "HealthMetricViewer":
        return HealthMetricViewer(self)

    @property
    def HealthPreference(self) -> "HealthPreferenceViewer":
        return HealthPreferenceViewer(self)


# #########################################################################
# Generated enums 0
# #########################################################################


# #########################################################################
# Generated classes 4
# #########################################################################


class AgentSuggestionAst:
    def __init__(self, tb: type_builder.TypeBuilder):
        _tb = tb._tb  # type: ignore (we know how to use this private attribute)
        self._bldr = _tb.class_("AgentSuggestion")
        self._properties: typing.Set[str] = set(
            [
                "summary",
                "meal_plan",
                "calorie_management",
                "weight_management",
                "hydration",
                "lifestyle",
            ]
        )
        self._props = AgentSuggestionProperties(self._bldr, self._properties)

    def type(self) -> baml_py.FieldType:
        return self._bldr.field()

    @property
    def props(self) -> "AgentSuggestionProperties":
        return self._props


class AgentSuggestionViewer(AgentSuggestionAst):
    def __init__(self, tb: type_builder.TypeBuilder):
        super().__init__(tb)

    def list_properties(
        self,
    ) -> typing.List[typing.Tuple[str, type_builder.ClassPropertyViewer]]:
        return [
            (name, type_builder.ClassPropertyViewer(self._bldr.property(name)))
            for name in self._properties
        ]


class AgentSuggestionProperties:
    def __init__(self, bldr: baml_py.ClassBuilder, properties: typing.Set[str]):
        self.__bldr = bldr
        self.__properties = properties  # type: ignore (we know how to use this private attribute) # noqa: F821

    @property
    def summary(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("summary"))

    @property
    def meal_plan(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("meal_plan"))

    @property
    def calorie_management(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(
            self.__bldr.property("calorie_management")
        )

    @property
    def weight_management(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(
            self.__bldr.property("weight_management")
        )

    @property
    def hydration(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("hydration"))

    @property
    def lifestyle(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("lifestyle"))


class HealthAgentContextAst:
    def __init__(self, tb: type_builder.TypeBuilder):
        _tb = tb._tb  # type: ignore (we know how to use this private attribute)
        self._bldr = _tb.class_("HealthAgentContext")
        self._properties: typing.Set[str] = set(
            [
                "metric",
                "preference",
            ]
        )
        self._props = HealthAgentContextProperties(self._bldr, self._properties)

    def type(self) -> baml_py.FieldType:
        return self._bldr.field()

    @property
    def props(self) -> "HealthAgentContextProperties":
        return self._props


class HealthAgentContextViewer(HealthAgentContextAst):
    def __init__(self, tb: type_builder.TypeBuilder):
        super().__init__(tb)

    def list_properties(
        self,
    ) -> typing.List[typing.Tuple[str, type_builder.ClassPropertyViewer]]:
        return [
            (name, type_builder.ClassPropertyViewer(self._bldr.property(name)))
            for name in self._properties
        ]


class HealthAgentContextProperties:
    def __init__(self, bldr: baml_py.ClassBuilder, properties: typing.Set[str]):
        self.__bldr = bldr
        self.__properties = properties  # type: ignore (we know how to use this private attribute) # noqa: F821

    @property
    def metric(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("metric"))

    @property
    def preference(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("preference"))


class HealthMetricAst:
    def __init__(self, tb: type_builder.TypeBuilder):
        _tb = tb._tb  # type: ignore (we know how to use this private attribute)
        self._bldr = _tb.class_("HealthMetric")
        self._properties: typing.Set[str] = set(
            [
                "weight_kg",
                "body_fat_percent",
                "bmi",
                "muscle_percent",
                "water_percent",
                "recorded_at",
                "note",
            ]
        )
        self._props = HealthMetricProperties(self._bldr, self._properties)

    def type(self) -> baml_py.FieldType:
        return self._bldr.field()

    @property
    def props(self) -> "HealthMetricProperties":
        return self._props


class HealthMetricViewer(HealthMetricAst):
    def __init__(self, tb: type_builder.TypeBuilder):
        super().__init__(tb)

    def list_properties(
        self,
    ) -> typing.List[typing.Tuple[str, type_builder.ClassPropertyViewer]]:
        return [
            (name, type_builder.ClassPropertyViewer(self._bldr.property(name)))
            for name in self._properties
        ]


class HealthMetricProperties:
    def __init__(self, bldr: baml_py.ClassBuilder, properties: typing.Set[str]):
        self.__bldr = bldr
        self.__properties = properties  # type: ignore (we know how to use this private attribute) # noqa: F821

    @property
    def weight_kg(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("weight_kg"))

    @property
    def body_fat_percent(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(
            self.__bldr.property("body_fat_percent")
        )

    @property
    def bmi(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("bmi"))

    @property
    def muscle_percent(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("muscle_percent"))

    @property
    def water_percent(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("water_percent"))

    @property
    def recorded_at(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("recorded_at"))

    @property
    def note(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("note"))


class HealthPreferenceAst:
    def __init__(self, tb: type_builder.TypeBuilder):
        _tb = tb._tb  # type: ignore (we know how to use this private attribute)
        self._bldr = _tb.class_("HealthPreference")
        self._properties: typing.Set[str] = set(
            [
                "target_weight_kg",
                "calorie_budget_kcal",
                "dietary_preference",
                "activity_level",
                "sleep_goal_hours",
                "hydration_goal_liters",
            ]
        )
        self._props = HealthPreferenceProperties(self._bldr, self._properties)

    def type(self) -> baml_py.FieldType:
        return self._bldr.field()

    @property
    def props(self) -> "HealthPreferenceProperties":
        return self._props


class HealthPreferenceViewer(HealthPreferenceAst):
    def __init__(self, tb: type_builder.TypeBuilder):
        super().__init__(tb)

    def list_properties(
        self,
    ) -> typing.List[typing.Tuple[str, type_builder.ClassPropertyViewer]]:
        return [
            (name, type_builder.ClassPropertyViewer(self._bldr.property(name)))
            for name in self._properties
        ]


class HealthPreferenceProperties:
    def __init__(self, bldr: baml_py.ClassBuilder, properties: typing.Set[str]):
        self.__bldr = bldr
        self.__properties = properties  # type: ignore (we know how to use this private attribute) # noqa: F821

    @property
    def target_weight_kg(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(
            self.__bldr.property("target_weight_kg")
        )

    @property
    def calorie_budget_kcal(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(
            self.__bldr.property("calorie_budget_kcal")
        )

    @property
    def dietary_preference(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(
            self.__bldr.property("dietary_preference")
        )

    @property
    def activity_level(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("activity_level"))

    @property
    def sleep_goal_hours(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(
            self.__bldr.property("sleep_goal_hours")
        )

    @property
    def hydration_goal_liters(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(
            self.__bldr.property("hydration_goal_liters")
        )
