# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions


from pydantic import BaseModel


CheckT = typing_extensions.TypeVar("CheckT")
CheckName = typing_extensions.TypeVar("CheckName", bound=str)


class Check(BaseModel):
    name: str
    expression: str
    status: str


class Checked(BaseModel, typing.Generic[CheckT, CheckName]):
    value: CheckT
    checks: typing.Dict[CheckName, Check]


def get_checks(checks: typing.Dict[CheckName, Check]) -> typing.List[Check]:
    return list(checks.values())


def all_succeeded(checks: typing.Dict[CheckName, Check]) -> bool:
    return all(check.status == "succeeded" for check in get_checks(checks))


# #########################################################################
# Generated enums (0)
# #########################################################################

# #########################################################################
# Generated classes (4)
# #########################################################################


class AgentSuggestion(BaseModel):
    summary: str
    meal_plan: typing.List[str]
    calorie_management: typing.List[str]
    weight_management: typing.List[str]
    hydration: typing.List[str]
    lifestyle: typing.List[str]


class HealthAgentContext(BaseModel):
    metric: "HealthMetric"
    preference: typing.Optional["HealthPreference"] = None


class HealthMetric(BaseModel):
    weight_kg: float
    body_fat_percent: float
    bmi: float
    muscle_percent: float
    water_percent: float
    recorded_at: str
    note: typing.Optional[str] = None


class HealthPreference(BaseModel):
    target_weight_kg: typing.Optional[float] = None
    calorie_budget_kcal: typing.Optional[int] = None
    dietary_preference: typing.Optional[str] = None
    activity_level: typing.Optional[str] = None
    sleep_goal_hours: typing.Optional[float] = None
    hydration_goal_liters: typing.Optional[float] = None


# #########################################################################
# Generated type aliases (0)
# #########################################################################
