# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

from . import types
from . import stream_types


type_map = {
    "types.AgentSuggestion": types.AgentSuggestion,
    "stream_types.AgentSuggestion": stream_types.AgentSuggestion,
    "types.HealthAgentContext": types.HealthAgentContext,
    "stream_types.HealthAgentContext": stream_types.HealthAgentContext,
    "types.HealthMetric": types.HealthMetric,
    "stream_types.HealthMetric": stream_types.HealthMetric,
    "types.HealthPreference": types.HealthPreference,
    "stream_types.HealthPreference": stream_types.HealthPreference,
}
